---
- name: Grant 'aegir' user access to system logs
  user:
    name: "{{ aegir_user }}"
    append: yes
    groups: adm

- name: Check if Valhalla modules are enabled
  shell: "drush @hm pm-info --fields=status --format=list {{ item }} | egrep 'disabled|not installed'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valhalla_cp_modules_enabled
  with_items: valhalla_cp_modules
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Enable Valhalla modules
  command: "drush @hm --yes en {{ item.1 }} --no-verify --strict=0"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  with_indexed_items: valhalla_cp_modules
  when: "valhalla_cp_modules_enabled.results[{{ item.0 }}].rc == 0"
  notify: Verify Aegir front-end

- name: Check if the cron-based task queue is enabled.
  shell: "drush @hm vget hosting_queue_tasks_enabled | grep 'false$'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valhalla_cp_cron_task_queue_check
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Disable cron-based task queue.
  command: drush @hm vset --format=boolean hosting_queue_tasks_enabled 0
  sudo: True
  sudo_user: "{{ aegir_user }}"
  when: valhalla_cp_cron_task_queue_check|failed

- name: Check if sites can be deleted without first being disabled
  shell: "drush @hm vget hosting_require_disable_before_delete | grep 'false$'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valhalla_cp_disable_before_delete_check
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Allow site deletion without disabling first.
  command: drush @hm vset --format=boolean hosting_require_disable_before_delete 0
  sudo: True
  sudo_user: "{{ aegir_user }}"
  when: valhalla_cp_disable_before_delete_check|failed
